In [7]:
import json
import numpy as np

dde_json = 'dde_scores.json'
with open(dde_json) as fp:
    dde = np.array(json.load(fp))

tr_json = 'tr_scores.json'
with open(tr_json) as fp:
    tr = np.array(json.load(fp))

In [22]:
dde.mean(0), tr.mean(0)

(array([0.80643944, 0.61206143, 0.36181663]),
 array([0.78341828, 0.58711517, 0.35235863]))

In [19]:
i = 8
dde[i], tr[i]

(array([0.93939394, 0.76262626, 0.37209302]),
 array([0.90909091, 0.6969697 , 0.32816537]))

In [20]:
dde.min(0), tr.min(0)

(array([0.46511628, 0.24170616, 0.09390863]),
 array([0.41666667, 0.20853081, 0.11286089]))

In [21]:
dde.max(0), tr.max(0)

(array([1.        , 0.92718447, 0.75510204]),
 array([0.97560976, 0.93457944, 0.74463519]))