In [25]:
import json
import pathlib
import numpy as np

jsons = pathlib.Path.cwd() / 'data' / 'jsons'

dde_json = jsons / 'dde_scores.json'
with open(dde_json) as fp:
    dde = np.array(json.load(fp))
    
gs_json = jsons / 'gs_scores.json'
with open(gs_json) as fp:
    gs = np.array(json.load(fp))

tr_json = jsons / 'tr_scores.json'
with open(tr_json) as fp:
    tr = np.array(json.load(fp))
    
lr_json = jsons / 'lr_scores.json'
with open(lr_json) as fp:
    lr = np.array(json.load(fp))

In [46]:
dde[dde == 0] = np.nan
np.nanmean(dde, 0), np.isnan(dde).sum() // 3

(array([0.8183164 , 0.6495861 , 0.40700852]), 0)

In [47]:
gs[gs == 0] = np.nan
np.nanmean(gs, 0), np.isnan(gs).sum() // 3

(array([0.80958321, 0.65230658, 0.41725812]), 9)

In [48]:
tr[tr == 0] = np.nan
np.nanmean(tr, 0), np.isnan(tr).sum() // 3

(array([0.80190613, 0.64122802, 0.39380937]), 7)

In [49]:
lr[lr == 0] = np.nan
np.nanmean(lr, 0), np.isnan(lr).sum() // 3

(array([0.76380854, 0.5868909 , 0.35080269]), 7)